---
- hosts: all
  gather_facts: false
  tasks:
    - name: ensure wget is installed
      yum:
        name: wget
        releasever: 1.19.5-10.el8
        state: present
        update_cache: true
        use_backend: dnf
      become: true
