---
- hosts: all
  gather_facts: false
  tasks:
    - name: ensure aalib is installed
      yum:
        name: aalib
        state: present
        update_cache: true
        use_backend: dnf
      become: true
