---
- hosts: all
  gather_facts: false
  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
        update_cache: true
        use_backend: dnf
      become: true
