---
- hosts: all
  gather_facts: false
  tasks:
    - name: ensure wget is installed
      yum:
        name: wget
        state: latest
        update_cache: true
        use_backend: dnf
      become: true
